config/routes.rb
USERNAME_ROUTE_FORMAT = /[A-Za-z0-9\_]+/ unless defined? USERNAME_ROUTE_FORMAT

Baiwale::Application.routes.draw do

  get "topics/show"

  get "topics/new"

  get "topics/create"

  get "topics/edit"

  get "topics/destory"

  resources :users do
    collection do
      put 'modify_password/:id' => 'users#modify_password'
    end
  end
  resources :discussions, id: USERNAME_ROUTE_FORMAT

  resources :topics do
    collection do
      post 'replay' => 'topics#replay'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  match "/about" => "home#about"
  match "/contact" => "home#contact"
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/signup', to: 'users#new'
  

  namespace :admin do
    get '/', :to => 'bpanel#index', :as => 'bpanel'
    resources :discussions
  end

  root :to => 'discussions#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :discussion_id, :last_replay_user_id, :post, :replies_count, :title, :user_id,
                  :views_count, :votes_count, :last_reply

  before_create :set_default_value

  belongs_to :user
  belongs_to :discussion

  has_many :replies, dependent: :destroy

  default_scope order: 'topics.last_reply DESC'

  def set_default_value
    self.last_reply = Time.now.strftime("%Y-%m-%d %H:%M:%S")
  end
end

app/controllers/topics_controller.rb
# -*- encoding: utf-8 -*-
class TopicsController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create, :replay]


  def new
    @topic = Topic.new
    @discussions = Discussion.all
  end

  def create
    @topic = current_user.topics.build(params[:topic])
    if @topic.save
      current_user.topics_count = current_user.topics.length
      current_user.save
      discussion = Discussion.find(@topic.discussion_id)
      discussion.topics_count = discussion.topics.length
      discussion.save
      redirect_to topic_path(@topic)
    else
      render 'new'
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @topic.views_count += 1
    @topic.save
    @replies = @topic.replies.paginate(page: params[:page], :per_page => 30)
    @reply = Reply.new
  end

  def edit
  end

  def destory
  end

  def replay
    @reply = current_user.replies.build(params[:reply])
    @reply.save
    topic = Topic.find(@reply.topic_id)
    topic.replies_count = topic.replies.length
    topic.last_reply = Time.now.strftime("%Y-%m-%d %H:%M:%S")
    topic.save
    current_user.replies_count = current_user.replies.length
    current_user.save
    redirect_to topic_path(@reply.topic_id)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_topic.html.erb
<li class="topic">
  <div class="fn-clear pdb10">
    <div class="num">
      <div class="num-answers votes"><strong><%= topic.replies_count %></strong><span>replies</span></div>
    </div>
    <div class="main fn-clear">
      <div class="user">
        <%= link_to image_tag(topic.user.avatar.url(:thumb), class: 'avatar'), user_path(topic.user), target: '_blank' %>
        <%= link_to topic.user.username, user_path(topic.user), target: '_blank' %>
      </div>
      <h2><%= link_to topic.title, topic_path(topic), target: '_blank' %></h2>
      <div class="tag">
        <%= link_to topic.discussion.title, discussion_path(topic.discussion.name) %>
        <span><%= topic.views_count %> Views</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span><%= topic.replies_count %> Replies</span>
        <div class="ago fr"><%= time_ago_in_words(topic.created_at) %></div>
      </div>
    </div>
  </div>
</li>

app/views/topics/create.html.erb
<%= @a %>

app/views/topics/destory.html.erb
<h1>Topics#destory</h1>
<p>Find me in app/views/topics/destory.html.erb</p>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/new.html.erb
<%= stylesheet_link_tag "topics", :media => "all" %>

<%= form_for(@topic) do |f| %>
  <div class="common-main-left">
    <!-- New Add -->
    <div class="m-add-question">
      <%= f.text_field :title, class: 'title qt', placeholder: 'title' %>
      <%= f.kindeditor :post, height: '480px', :allowFileManager => false, :editor_id => 'my_editor',
        :items => ["fontname","fontsize","|","forecolor","hilitecolor","bold","italic","underline","removeformat","|",
                   "justifyleft","justifycenter","justifyright","insertorderedlist","insertunorderedlist","|",
                   "emoticons","image","link","baidumap","source"]
      %>
    </div>
  </div>

  <div class="common-right">
    <div class="discussions_choose">
      <ul class="discuss-list mt15">
        <% @discussions.each do |d| %>
          <li>
            <%= f.radio_button(:discussion_id, d.id) %>
            <%= f.label("discussion_id_" + d.id.to_s, d.title) %>
          </li>
        <% end %>
      </ul>
    </div>
    <%= f.submit "发布", class: "btn" %>
  </div>
<% end %>

<script type="text/javascript">
$('form').submit(function(){
  var post = my_editor.html().replace(/<div id="xunlei_com_thunder_helper_plugin_d462f475-c18e-46be-bd10-327458d045bd">\n<\/div>/,'');
  $('#topic_post').val(post);
  if (!$('#topic_post').val()) {
    alert("请输入内容");
    return false;
  };
  if (!$('#topic_title').val()) {
    alert("请输入标题");
    return false;
  };
  if (!$("input:radio[name='topic[discussion_id]']:checked").val()) {
    alert("请选择板块");
    return false;
  };
});
</script>

app/views/topics/show.html.erb
<% provide(:title, @topic.title) %>

<%= stylesheet_link_tag "topics", :media => "all" %>

<div class="container w940 fn-clear">
  <!-- layout navigation -->
  <!-- <div class="navigation w940">首页 / 论坛 / 随便聊聊</div> -->
  <!--layout left-->
  <div class="common-left">
    <div class="topic-title"><%= @topic.title %></div>
    <!-- topic -->
    <div class="entry-topic">
      <div class="topic-info">
        <div class="user"><span class="time fl">
          <%= @topic.views_count %>views&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= time_ago_in_words(@topic.created_at) %></span>
          <%= link_to image_tag(@topic.user.avatar.url(:thumb), class: 'avatar'), user_path(@topic.user), target: '_blank' %>
          <%= link_to @topic.user.username, user_path(@topic.user), target: '_blank' %>
        </div>
        <!-- <div class="vote">
          <span class="num"><%#= @topic.votes_count %></span><a href="" class="agree">agree</a>
        </div> -->
      </div>
      <div class="topic-main">
        <%= @topic.post.html_safe %>
      </div>
    </div>
    <!-- Answers -->
    <div class="answer">
      <div class="answer-title"><h3><%= @topic.replies_count %> Anwsers</h3></div>
      <% if @replies %>
        <% @replies.each do |r| %>
          <div class="answer-con">
            <div class="topic-info">
              <div class="user"><span class="time fl"><%= time_ago_in_words(r.created_at) %></span>
                <%= link_to image_tag(r.user.avatar.url(:thumb), class: 'avatar'), user_path(r.user), target: '_blank' %>
                <%= link_to r.user.username, user_path(r.user), target: '_blank' %>
              </div>
            </div>
            <div class="topic-main"><%= r.post.html_safe %></div>
          </div>
        <% end %>
      <% end %>
    </div>
    <!-- Your Answer -->
    <div class="your-answer">
      <% if signed_in? %>
        <div class="answer-title"><h3>Your Answer</h3></div>
        <div class="your-answer-main fn-clear" style="margin-top:10px;">
          <%= form_for @reply, :url => {:controller => "topics", :action => "replay" } do |f| %>
            <%= f.kindeditor :post, :allowFileManager => false, :editor_id => 'my_editor',
              :items => ["fontname","fontsize","|","forecolor","hilitecolor","bold","italic","underline","removeformat","|",
                         "justifyleft","justifycenter","justifyright","insertorderedlist","insertunorderedlist","|",
                         "emoticons","image","link","baidumap","source"]
            %>
            <%= f.hidden_field :topic_id, value: @topic.id %>
            <%= f.submit "发布", class: "btn" %>
          <% end %>
        </div>
      <% else %>
        <div class="answer-title"><h3><%= link_to "回帖请先登陆", signin_path %></h3></div>
      <% end %>
    </div>
  </div>

  <!--layout right-->
  <div class="common-right">
  </div>
</div>

<script type="text/javascript">
$('form').submit(function(){
  var post = my_editor.html().replace('<div id="xunlei_com_thunder_helper_plugin_d462f475-c18e-46be-bd10-327458d045bd"> </div>','');
  post = post.replace('<div id="xunlei_com_thunder_helper_plugin_d462f475-c18e-46be-bd10-327458d045bd">\n</div>','');
  $('#reply_post').val(post);
  if (!$('#reply_post').val()) {
    alert("请输入内容");
    return false;
  };
});
</script>