config/routes.rb
USERNAME_ROUTE_FORMAT = /[A-Za-z0-9\_]+/ unless defined? USERNAME_ROUTE_FORMAT

Baiwale::Application.routes.draw do

  get "topics/show"

  get "topics/new"

  get "topics/create"

  get "topics/edit"

  get "topics/destory"

  resources :users do
    collection do
      put 'modify_password/:id' => 'users#modify_password'
    end
  end
  resources :discussions, id: USERNAME_ROUTE_FORMAT

  resources :topics do
    collection do
      post 'replay' => 'topics#replay'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  match "/about" => "home#about"
  match "/contact" => "home#contact"
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/signup', to: 'users#new'
  

  namespace :admin do
    get '/', :to => 'bpanel#index', :as => 'bpanel'
    resources :discussions
  end

  root :to => 'discussions#index'

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  attr_accessible :title, :name, :summary

  has_many :topics, dependent: :destroy
  
  default_scope order: 'discussions.topics_count DESC'
end

app/controllers/admin/discussions_controller.rb
class Admin::DiscussionsController < Admin::BaseController
  def index
    @discussions = Discussion.all
  end

  def show
    
  end

  def new
    @discussion = Discussion.new
  end

  def create
    @discussion = Discussion.new(params[:discussion])
    if @discussion.save
      redirect_to admin_discussions_path
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    
  end

  def destory
    
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

  def index
    @discussions = Discussion.all
    @topics = Topic.paginate(page: params[:page], :per_page => 30)
  end

  def show
    @discussions = Discussion.all
    @discussion = Discussion.find_by_name(params[:id])
    @topics = @discussion.topics.paginate(page: params[:page], :per_page => 30)
  end
  
  def edit

  end

end

app/helpers/admin/discussions_helper.rb
module Admin::DiscussionsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/admin/discussions/_discussion.html.erb
<tr <% if discussion_counter % 2 == 0 %> class="odd" <% end %> >
  <td><%= discussion.id %></td>
  <td><%= discussion.title %></td>
  <td><%= discussion.name %></td>
  <td><%= discussion.topics_count %></td>
</tr>

app/views/admin/discussions/index.html.erb
<div class="btn_blk">
  <div class="fr">
    <%= link_to "新建栏目", new_admin_discussion_path, class: 'btn1 fr' %>
  </div>
</div>

<table width="100%" class="table_list">
  <tr>
    <th width="25%">语言</th>
    <th width="25%">首页</th>
    <th width="25%">标题</th>
    <th width="25%">类型</th>
  </tr>
  <%= render @discussions %>
</table>

app/views/admin/discussions/new.html.erb
<%= form_for(@discussion, :url => admin_discussions_path) do |f| %>

  <div class="con_blk">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'txt_field' %>
  </div>

  <div class="con_blk">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'txt_field' %>
  </div>

  <div class="con_blk">
    <%= f.label :summary %>
    <%= f.text_field :summary, class: 'txt_field' %>
  </div>

  <div class="con_blk">
    <%= f.submit '确定', class: 'btn1 fr save' %>
  </div>

<% end %>