config/routes.rb
USERNAME_ROUTE_FORMAT = /[A-Za-z0-9\_]+/ unless defined? USERNAME_ROUTE_FORMAT

Baiwale::Application.routes.draw do

  get "topics/show"

  get "topics/new"

  get "topics/create"

  get "topics/edit"

  get "topics/destory"

  resources :users do
    collection do
      put 'modify_password/:id' => 'users#modify_password'
    end
  end
  resources :discussions, id: USERNAME_ROUTE_FORMAT

  resources :topics do
    collection do
      post 'replay' => 'topics#replay'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  match "/about" => "home#about"
  match "/contact" => "home#contact"
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/signup', to: 'users#new'
  

  namespace :admin do
    get '/', :to => 'bpanel#index', :as => 'bpanel'
    resources :discussions
  end

  root :to => 'discussions#index'

end

app/views/layouts/_footer.html.erb
<div class="footer">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41499608-1', 'baiwale.com');
  ga('send', 'pageview');
</script>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="nav w940">
    <h1 class="title fl"><%= link_to "Baiwale", root_path %></h1>
    <ul class="fl pl20">
      <!-- <li><%#= link_to "首页", root_path %></li> -->
      <li><%= link_to "讨论组", discussions_path %></li>
    </ul>
    <ul class="fr">
      <% if signed_in? %>
        <li><%= link_to current_user.username, current_user %></li>
        <!-- <li><a href="#">通知</a></li> -->
        <li><%= link_to "发帖", new_topic_path %></li>
        <li><%= link_to "登出", signout_path %></li>
      <% else %>
        <li><%= link_to "登入", signin_path %></li>
        <li><%= link_to "注册", signup_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>后台管理</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <%= stylesheet_link_tag    "admin_style", :media => "all" %>
  <%= stylesheet_link_tag    "admin_layout", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--header start-->
<div class="header"> <a href="admin.html">白挖了</a>
  <div class="header_login clearfix">
  <a href="admin/user/logout" class="btn_logout">登出</a>
  </div>
</div>
<!--header end-->
<div class="container clearfix">
  <div class="sidebar">
    <dl class="sidemenu show">
      <dd><%= link_to '首页管理', admin_bpanel_path %></dd>
      <dd><%= link_to '论坛管理', admin_discussions_path %></dd>
      <dd><a href="admin/term.html">团队管理</a></dd>
      <dd><a href="admin/contents.html">文章管理</a></dd>
      <dd><a href="admin/contact.html">联系我们</a></dd>
      <dd><a href="admin/about.html">关于我们</a></dd>
      <dd><a href="admin/jobs.html">加入我们</a></dd>
      <dd><a href="admin/lang.html">语言管理</a></dd>
    </dl>
  </div>
  <div class="main clearfix">
    <div class="main_con">
    <%= yield %>
    </div>
  </div>
  <div class="footer">
    <p>&nbsp;</p>
  </div>
</div>
</body>
<%#= debug(params) if Rails.env.development? %>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "home", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container w940 fn-clear">
    <div class='flash_message'>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class:"alert alert-#{key}") %>
      <% end %>
    </div>
    
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%#= debug(params) if Rails.env.development? %>
</body>
</html>